[package]
name = "leptos-csr"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "0.1.7"
console_log = "0.2.0"
leptos = "0.1.3"
leptos_meta = { version = "0.1.3", features = ["csr"] }
leptos_router = { version = "0.1.3", features = ["csr"] }
log = "0.4.17"
wasm-bindgen = "0.2.84"

[package.metadata.leptos]
site-root = "."
